### ISSUE TITLE
When the string of replies/comments goes below the bottom of the screen, typing is "blind"

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#48]
These both appears to be bugs with the editor.

When comments or replies are added below a post such that in aggregate they take up more than one screen's worth of real estate, you are forced to type "blind" since the screen automatically jumps upward and you can no longer see what you are typing without stopping, scrolling the screen manually, and looking at what you just typed.  And then as soon as you start typing again, the screen once again jumps upward.

Similarly, when any post is made and the typing goes below the designated size of the editor box, the new typing cannot be seen as that which was already typed does not scroll automatically.

**Comment by chrispittman** [comment]
Thanks for letting us know!

The first is something we can fix by slightly altering how we ask ToastUI (the editor we're using) to give us the text you're typing.

The second is a bug in ToastUI, which was fixed in version 3.0.2, which got released a few days ago.  I'll update.

Should have fixes for both of these out in a day or two.

**Comment by dpassovoy** [comment]
Quick response — thanks!

**Comment by chrispittman** [comment]
Think I have a code fix.  Asking UT Austin to do some quick internal testing, and they should release the new version by end of day today.
